---
# defaults file for openvpn

openvpn_version: 2.3.11

openvpn_static: true

openvpn_client: false
openvpn_server: false

openvpn_auth_enable: false

openvpn_client_endpoint: 172.16.21.2
openvpn_server_endpoint: 172.16.21.1
openvpn_client_ifconfig: "{{ openvpn_client_endpoint }} {{ openvpn_server_endpoint }}"
openvpn_server_ifconfig: "{{ openvpn_server_endpoint }} {{ openvpn_client_endpoint }}"

openvpn_cipher: AES-256-CBC
openvpn_auth: SHA1
openvpn_lport: 9985
openvpn_pull: false
openvpn_dev: tun
openvpn_comp_lzo: true
openvpn_daemon: true
openvpn_keepalive: '10 60'
openvpn_nobind: true
openvpn_persist_key: true
openvpn_persist_tun: true
openvpn_ping_timer_rem: true
openvpn_proto: udp
openvpn_remote_host: 'vpn.friendswoodmetals.com'
openvpn_remote_port: 9985
openvpn_remote_proto: "udp"
openvpn_resolv_retry: infinite
openvpn_secret: ''
openvpn_verb: 3
openvpn_status: /var/log/openvpn-status.log
openvpn_log_append:  /var/log/openvpn.log
openvpn_route1: ''
openvpn_route2: ''
openvpn_route3: ''
openvpn_packages:
  - openvpn
openvpn_service_name: openvpn
openvpn_user: nobody
openvpn_group: nogroup
