---
- hosts: adm
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    apt_packages:
      - docker
      - nut
  roles:
    - apt 
    - hostname
    - ntp
    - ssh
    - timezone
    - users
    - sudo
    - ufw
    - docker
