---
- hosts: server
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    ufw_rules:
      - { port: 22, rule: allow }
      - { port: 1194, rule: allow }

  roles:
    - apt 
    - hostname
    - ntp
    - ssh
    - timezone
    - users
    - ufw
    - nat
    - openvpn
