---

- name: Compatibility check
  fail: msg="This role only works on Debian systems"
  when: not ansible_os_family == "Debian"

- include: install.yml
- include: config.yml
- include: service.yml
  tags: [ufw]
