---
  - name: Update the distro
    apt: upgrade=yes update_cache=yes cache_valid_time=3600


  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items:
      - "{{ common_packages }}"
