---
# tasks file for openvpn

#- name: Include distribution specific variables
#  include_vars: "{{ ansible_distribution }}.yml"
#  tags:
#    - openvpn

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  become: yes
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "trusty"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  become: yes
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - openvpn

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart openvpn
  when: openvpn_client
  tags:
    - openvpn

- name: Create OpenVPN server configuration file
  become: yes
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart openvpn
  when: openvpn_server
  tags:
    - openvpn

- name: Create OpenVPN static key
  become: yes
  template:
    src: static.key.j2
    dest: "{{ openvpn_secret_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart openvpn
  when: openvpn_static
  tags:
    - openvpn

- name: Ensure OpenVPN service is started and enabled on boot
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: started
    enabled: yes
  tags:
    - openvpn
